config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :weather_grid

  get "/subscriptions/cancel_subscription"  => "subscriptions#cancel_subscription"
  get "/subscriptions/update_card"          => "subscriptions#update_card"
  post "/subscriptions/update_card_details" => "subscriptions#update_card_details"

  resources :subscriptions


  root to: "home#index"

  mount StripeEvent::Engine, at: '/stripe-event' # provide a custom path

end

app/models/account.rb
class Account < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :async

  validate :email_is_unique, on: :create
  after_create :create_account

  #def confirmation_required?
  #  false
  #end

  private
  # Email should be unique in Account model
  def email_is_unique
    #don't validate email if any error present
    return false unless self.errors[:email].empty?
    unless Account.find_by_email(email).nil?
      errors.add(:email, " is already used")
    end
  end

  def create_account
    account = Account.new(email: email)
    account.save!
  end
  
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #helper ApplicationHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @message = "Welcome user"
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @account = Account.find_by_email(current_user.email)
  end

  def new
    @plans = Plan.all.order(:id)
  end

  def edit
    @account = Account.find(params[:id])
    @plans = Plan.all.order(:id)
  end

  def create
    #byebug
    #ap "Inside create in subscription. See params hash"
    #ap params
    #byebug
    token = params[:stripeToken]
    plan = params[:plan][:stripe_id]
    email = current_user.email
    current_account = Account.find_by_email(current_user.email)
    customer_id = current_account.customer_id
    current_plan = current_account.stripe_plan_id

    if customer_id.nil?
      #new customer -> Create customer
      @customer = Stripe::Customer.create(
          :source => token,
          :plan => plan,
          :email => email
      )
      subscriptions = @customer.subscriptions
      @subscribed_plan = subscriptions.data.find {|o| o.plan.id == plan}

    else
      #Customer exists
      #Get customer from Stripe
      @customer = Stripe::Customer.retrieve(customer_id)
      @subscribed_plan = create_or_update_subscription(@customer, current_plan, plan)
    end


    #In unix timestamp
    current_period_end = @subscribed_plan.current_period_end
    #Convert to datetime
    active_until = Time.at(current_period_end).to_datetime


    save_account_details(current_account, plan, @customer.id, active_until)

    redirect_to :root, :notice => "Successfully subscribed to a plan #{current_account.stripe_plan_id}"

  rescue => e
    redirect_to :back, :flash => {:error => e.message}
  end

  def cancel_subscription
    email = current_user.email
    current_account = Account.find_by_email(current_user.email)
    customer_id = current_account.customer_id
    current_plan = current_account.stripe_plan_id

    if current_plan.blank?
      raise "No plans found to unsubscribe/cancel"
    end
    #Fetch customer from stripe
    customer = Stripe::Customer.retrieve(customer_id)
    #Get customer's subscriptions
    subscriptions = customer.subscriptions
    #Find subscription that we want to cancel
    current_subscribed_plan = subscriptions.data.find {|o| o.plan.id == current_plan}
    if current_subscribed_plan.blank?
      raise "Subscription not found!!!"
    end
    #Delete it
    current_subscribed_plan.delete
    #Update account model
    save_account_details(current_account, "", customer_id, Time.at(0).to_datetime)
    @message = "Subscription was canceled successfully"
  rescue => e
    redirect_to "/subscriptions", :flash => {:error => e.message}
  end

  def update_card

  end

  def update_card_details
    #take the token given by stripe and set it on customer
    token = params[:stripeToken]
    #Get customer id current_account = Account.find_by_email(current_user.email)
    current_account = Account.find_by_email(current_user.email)
    customer_id = current_account.customer_id
    #Get customer from stripe
    customer = Stripe::Customer.retrieve(customer_id)
    #set new card token
    customer.source = token
    customer.save

    redirect_to "/subscriptions", :notice => "Card updated successfully"
  rescue => e
    redirect_to :action => "update_card", :flash => { :error => e.message }

  end

  def save_account_details(account, plan, customer_id, active_until)
    #Update account with the details
    account.stripe_plan_id = plan
    account.customer_id = customer_id
    account.active_until = active_until
    account.save!
  end

  def create_or_update_subscription(customer, current_plan, new_plan)
    #byebug
    subscriptions = customer.subscriptions
    #Get subscription
    current_subscription = subscriptions.data.find {|o| o.plan.id == current_plan}
    if current_subscription.blank?
      #No current subscription
      #maybe the customer unsubscribed previously or maybe the card was declined
      #So, create new subscription to existing customer
      subscription = customer.subscriptions.create({:plan => new_plan})
    else
      #existing subscriptionn found
      #must be upgrade pr downgrade
      #So update existing subscription with new plan
      current_subscription.plan = new_plan
      subscription = current_subscription.save
    end
    return subscription
  end
end

app/controllers/weather_grid_controller.rb
class WeatherGridController < ApplicationController
  before_action :authenticate_user!
  def index
    # ...
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_lass_for flash_type
    case flash_type
      when "success"
        "alert-success" #green
      when "error"
        "alert-danger" #red
      when "alert"
        "alert-warning" #yellow
      when "notice"
        "alert-info" #blue
      else
        flash_type.to_s
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/weather_grid_helper.rb
module WeatherGridHelper
end

app/views/home/index.html.erb
<%= link_to('Login', new_user_session_path) %>
<%= link_to('Logout', destroy_user_session_path, method: :delete ) %>
<%= link_to('Sign up', new_user_registration_path) %>
<%= link_to('Manage Subscriptions', subscriptions_path) %>

<h1><%= @message %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaasGuide</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<!--<p class="notice"><#%= notice %></p>-->
<!--<p class="alert"></p>-->


<% flash.each do |type, message| %>
    <div class="alert <%= bootstrap_lass_for(type)%> alert-dismissible" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span></button>
    </div>
<% end %>
<%= yield %>
</body>
</html>

app/views/subscriptions/_creditcard.html.erb
<%= javascript_include_tag "https://js.stripe.com/v2/"%>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_tag "/subscriptions", id: "payment-form" do %>

      <span class="payment-errors text-danger"></span>

        <%= collection_select :plan, :stripe_id, @plans, :stripe_id, :name, {}, {class: "form-control"}%>

      <div class="form-group">
        <label for="number">Card Number</label>
        <input type="text" size="20" class="form-control" id="number" data-stripe="number">
      </div>

      <div class="form-group">
        <label for="cvc">CVC</label>
        <input type="text" size="4" class="form-control" id="cvc" data-stripe="cvc">
      </div>

      <label for="exp">Expiration (MM/YYYY)</label>
      <div class="form-group">
        <div>
          <input type="text" size="2" class="form-control exp-field" id="exp" data-stripe="exp-month">
          <span> / </span>
          <input type="text" size="4" class="form-control exp-field" data-stripe="exp-year">
        </div>

      </div>
      <button type="submit" class="btn btn-primary">Submit Payment</button>
   <% end %>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
   Stripe.setPublishableKey("<%= Rails.configuration.stripe[:publishable_key]%>");
</script>

app/views/subscriptions/_plans.html.erb
<div class="row">
  <div class="col-sm-2 col-sm-offset-3">
    <div class="plan_box">
      <h3>Plan Free</h3>
      <p>1 dollar
        <br>
        Good for evaluation
      </p>

    </div>
  </div>
  <div class="col-sm-2">
    <div class="plan_box">
      <h3>Plan Good</h3>
      <p>
        <br>Everything in free
        <br>Good plan for small businesses
      </p>
      <br>
    </div>
  </div>
  <div class="col-sm-2">
    <div class="plan_box">
      <h3>Plan Awesome</h3>
      <p>
        <br>Everithing in Plan Good
        <br>Good for enterprises
      </p>

    </div>
  </div>
</div>

app/views/subscriptions/cancel_subscription.html.erb
<h1>Cancel Subscription</h1>
<p>
  <%= @message %>
</p>

app/views/subscriptions/create.html.erb
<h1>Inside create </h1>

app/views/subscriptions/edit.html.erb
Please choose your new plan:
<br>
<%= render :partial => 'plans' %>
<div class="row col-sm-3 col-sm-offset-3">
  <%= form_tag "/subscriptions" do %>
      <%= collection_select :plan, :stripe_id, @plans, :stripe_id, :name, {}, {class: "form-control"} %>
      <br>
      <button type="submit" class="btn btn-primary">Update Subscription</button>
  <% end %>
</div>


app/views/subscriptions/index.html.erb
<% if @account.stripe_plan_id %>
    <% if @account.active_until > Time.now %>
        Your subscription is active until <%= @account.active_until %>
    <% else %>
        Your subscription expired on <%= @account.active_until %>
    <% end %>

<% else %>
    You do not have subscription plan.
<% end %>

<br>

<%= link_to 'Change Subscription', edit_subscription_path(@account.id), {class: "btn btn-primary"} %>
<br>
<br>
<%= link_to 'Cancel Subscription', subscriptions_cancel_subscription_path, {class: "btn btn-primary"} %>
<br>
<br>
<%= link_to 'Update card', subscriptions_update_card_path, {class: "btn btn-primary"} %>
<br>
<br>
<%= link_to 'New subscription', new_subscription_path, {class: "btn btn-primary"} %>


app/views/subscriptions/new.html.erb
<%= render :partial => 'plans' %>
<%= render :partial => 'creditcard' %>

app/views/subscriptions/update_card.html.erb
<%= javascript_include_tag "https://js.stripe.com/v2/"%>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <%= form_tag "/subscriptions/update_card_details", id: "payment-form" do %>

        <span class="payment-errors text-danger"></span>

        <div class="form-group">
          <label for="number">Card Number</label>
          <input type="text" size="20" class="form-control" id="number" data-stripe="number">
        </div>

        <div class="form-group">
          <label for="cvc">CVC</label>
          <input type="text" size="4" class="form-control" id="cvc" data-stripe="cvc">
        </div>

        <label for="exp">Expiration (MM/YYYY)</label>
        <div class="form-group">
          <div>
            <input type="text" size="2" class="form-control exp-field" id="exp" data-stripe="exp-month">
            <span> / </span>
            <input type="text" size="4" class="form-control exp-field" data-stripe="exp-year">
          </div>

        </div>
        <button type="submit" class="btn btn-primary">Submit Payment</button>
    <% end %>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    Stripe.setPublishableKey('pk_test_AQYeROOdB1B92kMif5tbBaEV');
</script>

app/views/weather_grid/index.html.erb
<h1>Weather Grid index</h1>